# Whitespace
name: Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to (dev is actually prod, test is test)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - test
env:
  AWS_REGION: "us-east-1"
permissions:
  id-token: write
  contents: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::553590173470:role/thecommoncoder-github-actions
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.6
      - name: Terraform Init
        run: terraform init
      - name: Terraform Set Workspace
        run: terraform workspace select us-east-1.${{ github.event.inputs.environment }}-minecraft-server
      - name: Terraform Plan
        run: terraform plan -out tfplan
      - name: Terraform Apply
        run: terraform apply tfplan